#!/bin/sh
# Tony
# Generate python file in $(PWD).
# cp newpy /usr/local/bin/ && chmod +x newpy

home=$(pwd)
echo "dir: "${home}
if [[ $# -lt 1 ]]; then
    echo "we will generate py_demo.py"
    cp ~/py_demo.py ${home}/ 
else
    echo "we will generate $1"
    cp ~/py_demo.py ${home}/$1 
fi
